name: asset
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    

flutter_icons:
  



flutter:
  assets:
  - gambar/images.png
  - gambar/pr.png

  uses-material-design: true

  